# Generated by Django 3.2 on 2021-05-08 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meetingAgenda',
            new_name='Agenda',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='meetingdate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='meetinglocation',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='meetingtime',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='meetingtitle',
            new_name='title',
        ),
    ]
