# Generated by Django 3.2 on 2021-05-08 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20210507_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingminutes',
            name='agenda',
        ),
    ]
